/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.danny270793.test;

public class App {
    public static int fibonacci(int n) {
        if (n <= 1) {
            return n;
        } else {
            return fibonacci(n - 1) + fibonacci(n - 2);
        }
    }

    public static void main(String[] args) {
        try {
            final int desired = Integer.parseInt(args[0]);
            final int result = App.fibonacci(desired);

            System.out.println("Fibonacci(" + desired + "): " + result);
        } catch(Exception exception) {
            exception.printStackTrace();
        }
    }
}
